### ISSUE TITLE
Lineage B.5 is not monophyletic

### ISSUE THREAD

**Issue by joshsinger** [hCoV-2019/lineages#1]
I recomputed the alignment / tree (exclude 5' and 3' UTRs, MAFFT, RAxML 1000 bootstraps, model GTRGAMMAI) and found that lineage B.5 is not monophyletic in my tree. I had a look in anonymised.aln.fasta.treefile and found that B.5 is not monophyletic there either. All other lineages were monophyletic in my tree, did not check anonymised.aln.fasta.treefile any further.

I'm guessing B.5 will be dropped soon as it is looking a bit old?

**Comment by aineniamh** [comment]
Hi Josh, I've just made an updated release. You're right about B.5, rather than dropping it I've refined it slightly and only included the sequences shown in pink here. Previously the US sequences were also included in this definition. The new guide tree is monophyletic for this lineage now and metadata suggests this really is a lineage, despite the borderline bootstrap.  Thanks for pointing it out though. Happy to discuss though if you have another suggestion!
<img width="382" alt="Screenshot 2020-05-07 23 30 15" src="https://user-images.githubusercontent.com/11678307/81350906-ed6ecd80-90ba-11ea-9540-f0a904195175.png">
